import os
from dotenv import load_dotenv

load_dotenv()


API_CALL_PRICE_MICRO = 1000
INPUT_TOKEN_PRICE_MICRO = 100
CACHED_INPUT_TOKEN_PRICE_MICRO = 25
OUTPUT_TOKEN_PRICE_MICRO = 200


STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET")
STRIPE_PRO_PRICE_ID = os.getenv("STRIPE_PRO_PRICE_ID")